name: Build Status Check

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    
    - name: Build Service Registry
      run: |
        if [ -d "service-registory" ]; then
          cd service-registory
          mvn clean install -DskipTests
        else
          echo "Service Registry directory not found, skipping build"
        fi
      continue-on-error: true
    
    - name: Build Auth Service
      run: |
        if [ -d "services/auth-service" ]; then
          cd services/auth-service
          mvn clean install -DskipTests
        else
          echo "Auth Service directory not found, skipping build"
        fi
      continue-on-error: true
    
    # Add more services here as they are added to the project
    
    - name: Update PR with build status
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const { owner, repo } = context.repo;
          const { number } = context.issue;
          
          github.rest.issues.createComment({
            owner,
            repo,
            issue_number: number,
            body: '✅ All services build successfully!'
          });
